version: "3.9"

services:
  sequencer-log-platform:
    build: .
    container_name: sequencer-log-platform
    ports:
      - "8000:8000"
      - "1122:1122"
    volumes:
      - ./.env:/workspace/.env
      - ./.env.example:/workspace/.env.example:ro
      - ./data:/workspace/data
      - ./config:/workspace/config
